import { useEffect, useState } from "react";
import api from "../utils/api";

export default function GeminiAnalysis() {
  const [analysis, setAnalysis] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get("/gemini-analysis").then((res) => {
      setAnalysis(res.data.analysis);
      setLoading(false);
    });
  }, []);

  return (
    <>
      <h1>AI community analysis</h1>
      <p>Generated by Gemini from recent complaint activity.</p>

      <div className="card section-gap" style={{ padding: 24 }}>
        {loading ? (
          <p className="loading-state" style={{ padding: "20px 0" }}>
            Generating analysis…
          </p>
        ) : (
          <pre className="analysis-pre">{analysis}</pre>
        )}
      </div>
    </>
  );
}
