import { useEffect, useState } from "react";
import api from "../utils/api";

export default function GeminiAnalysis() {
  const [analysis, setAnalysis] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get("/gemini-analysis")
      .then((res) => {
        setAnalysis(res.data.analysis);
      })
      .catch((err) => {
        console.error("Failed to load Gemini analysis", err);
        setAnalysis("Failed to generate community analysis. Please check your network connection or try again later.");
      })
      .finally(() => {
        setLoading(false);
      });
  }, []);

  return (
    <>
      <h1>AI community analysis</h1>
      <p>Generated by Gemini from recent complaint activity.</p>

      <div className="card section-gap" style={{ padding: 24 }}>
        {loading ? (
          <p className="loading-state" style={{ padding: "20px 0" }}>
            Generating analysis…
          </p>
        ) : (
          <pre className="analysis-pre">{analysis}</pre>
        )}
      </div>
    </>
  );
}
